disabled_rules:
  - line_length
  - trailing_comma
  - operator_whitespace
  - trailing_whitespace

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Example
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Example/Pods
  - Tests
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1000
type_body_length:
  warning: 500
  error: 1000
shorthand_operator:
  severity: warning
force_cast:
  severity: warning
